name: CI

on:
  pull_request:
    branches:
      - master
      - develop

  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Black 3.8
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "glow -tpy38 -l80 --check"

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Flake8
        run: |
          pip install flake8 && \
          flake8 --select=C,E,F,W \
            --max-line-length 80 \
            --max-complexity 10
